@echo off
echo Deleting old us-central1 functions...

firebase functions:delete addTechnicianService --region us-central1 --force
firebase functions:delete adminApproveBooking --region us-central1 --force
firebase functions:delete adminApproveServiceRequest --region us-central1 --force
firebase functions:delete adminRejectBooking --region us-central1 --force
firebase functions:delete adminUpdateBankStatus --region us-central1 --force
firebase functions:delete adminUpdateDocumentStatus --region us-central1 --force
firebase functions:delete admin_adjustWallet --region us-central1 --force
firebase functions:delete admin_approveKYC --region us-central1 --force
firebase functions:delete admin_approveService --region us-central1 --force
firebase functions:delete admin_approveTechnician --region us-central1 --force
firebase functions:delete admin_approveTechnicianApplication --region us-central1 --force
firebase functions:delete admin_auditServiceCatalog --region us-central1 --force
firebase functions:delete admin_backfillImages --region us-central1 --force
firebase functions:delete admin_blockUser --region us-central1 --force
firebase functions:delete admin_disableService --region us-central1 --force
firebase functions:delete admin_getDashboardStats --region us-central1 --force
firebase functions:delete admin_getTechnicianById --region us-central1 --force
firebase functions:delete admin_getTechnicians --region us-central1 --force
firebase functions:delete admin_getUserById --region us-central1 --force
firebase functions:delete admin_getUsers --region us-central1 --force
firebase functions:delete admin_initializeHomeContent --region us-central1 --force
firebase functions:delete admin_manageBooking --region us-central1 --force
firebase functions:delete admin_manageCategory --region us-central1 --force
firebase functions:delete admin_manageDispute --region us-central1 --force
firebase functions:delete admin_manageHomeSections --region us-central1 --force
firebase functions:delete admin_manageNestedService --region us-central1 --force
firebase functions:delete admin_manageNestedSubService --region us-central1 --force
firebase functions:delete admin_manageReview --region us-central1 --force
firebase functions:delete admin_manageRiskProfile --region us-central1 --force
firebase functions:delete admin_manageService --region us-central1 --force
firebase functions:delete admin_manageUser --region us-central1 --force
firebase functions:delete admin_processBookingPayout --region us-central1 --force
firebase functions:delete admin_refundBooking --region us-central1 --force
firebase functions:delete admin_rejectService --region us-central1 --force
firebase functions:delete admin_sendPushNotification --region us-central1 --force
firebase functions:delete admin_suspendTechnician --region us-central1 --force
firebase functions:delete admin_toggleTechAvailability --region us-central1 --force
firebase functions:delete admin_updateTechServices --region us-central1 --force
firebase functions:delete admin_updateTechnician --region us-central1 --force
firebase functions:delete admin_updateUser --region us-central1 --force
firebase functions:delete admin_uploadServiceImage --region us-central1 --force
firebase functions:delete approveBooking --region us-central1 --force
firebase functions:delete approveBookingByAdmin --region us-central1 --force
firebase functions:delete approveBookingRequest --region us-central1 --force
firebase functions:delete approveKYC --region us-central1 --force
firebase functions:delete approveTechnician --region us-central1 --force
firebase functions:delete approveWithdrawal --region us-central1 --force
firebase functions:delete assignTechnician --region us-central1 --force
firebase functions:delete assignTechnicianToBooking --region us-central1 --force
firebase functions:delete cancelBooking --region us-central1 --force
firebase functions:delete checkKycStatus --region us-central1 --force
firebase functions:delete clearCartCallable --region us-central1 --force
firebase functions:delete completeBooking --region us-central1 --force
firebase functions:delete completeService --region us-central1 --force
firebase functions:delete confirmQRPayment --region us-central1 --force
firebase functions:delete createBookingIdempotent --region us-central1 --force
firebase functions:delete createBookingRequest --region us-central1 --force
firebase functions:delete createCustomServiceRequest --region us-central1 --force
firebase functions:delete createRazorpayOrder --region us-central1 --force
firebase functions:delete createService --region us-central1 --force
firebase functions:delete createSubService --region us-central1 --force
firebase functions:delete createTechnicianProfile --region us-central1 --force
firebase functions:delete createTechnicianService --region us-central1 --force
firebase functions:delete customerConfirmServicePayment --region us-central1 --force
firebase functions:delete deleteAllNotificationsCallable --region us-central1 --force
firebase functions:delete deleteNotificationCallable --region us-central1 --force
firebase functions:delete deleteService --region us-central1 --force
firebase functions:delete deleteSubService --region us-central1 --force
firebase functions:delete evaluateTechnicianKyc --region us-central1 --force
firebase functions:delete findEligibleTechniciansCount --region us-central1 --force
firebase functions:delete generateBookingQR --region us-central1 --force
firebase functions:delete generateTechnicianQR --region us-central1 --force
firebase functions:delete generateWeeklyPayoutReport --region us-central1 --force
firebase functions:delete getChatDetails --region us-central1 --force
firebase functions:delete getCustomRequestDetail --region us-central1 --force
firebase functions:delete getInstantServices --region us-central1 --force
firebase functions:delete getMyTechnicianServices --region us-central1 --force
firebase functions:delete getOrCreateChat --region us-central1 --force
firebase functions:delete getPayoutHistory --region us-central1 --force
firebase functions:delete getPayoutSummary --region us-central1 --force
firebase functions:delete getPendingPayouts --region us-central1 --force
firebase functions:delete getPendingWithdrawalRequests --region us-central1 --force
firebase functions:delete getReconciliationAnomalies --region us-central1 --force
firebase functions:delete getSubServicePriceHistory --region us-central1 --force
firebase functions:delete getTechnicianEarnings --region us-central1 --force
firebase functions:delete getTechnicianInbox --region us-central1 --force
firebase functions:delete getTechnicianPayoutHistory --region us-central1 --force
firebase functions:delete getTransactionHistory --region us-central1 --force
firebase functions:delete getWithdrawalRequests --region us-central1 --force
firebase functions:delete initiateRazorpayPayment --region us-central1 --force
firebase functions:delete initiateRefund --region us-central1 --force
firebase functions:delete manageAddress --region us-central1 --force
firebase functions:delete manageAddressSecure --region us-central1 --force
firebase functions:delete managePaymentMethod --region us-central1 --force
firebase functions:delete markAllNotificationsRead --region us-central1 --force
firebase functions:delete markBookingActive --region us-central1 --force
firebase functions:delete markMessagesRead --region us-central1 --force
firebase functions:delete markNotificationRead --region us-central1 --force
firebase functions:delete markWalletReviewed --region us-central1 --force
firebase functions:delete matchTechniciansV2 --region us-central1 --force
firebase functions:delete migrateBookingStatusFunction --region us-central1 --force
firebase functions:delete onBookingCompletedAwardReferral --region us-central1 --force
firebase functions:delete refundBookingPayment --region us-central1 --force
firebase functions:delete rejectBooking --region us-central1 --force
firebase functions:delete rejectWithdrawal --region us-central1 --force
firebase functions:delete removeFcmToken --region us-central1 --force
firebase functions:delete removeFromCartCallable --region us-central1 --force
firebase functions:delete requestWithdrawal --region us-central1 --force
firebase functions:delete respondToAssignment --region us-central1 --force
firebase functions:delete reuploadVerificationDocument --region us-central1 --force
firebase functions:delete saveFcmToken --region us-central1 --force
firebase functions:delete saveTechnicianBasicDetails --region us-central1 --force
firebase functions:delete saveTechnicianDocuments --region us-central1 --force
firebase functions:delete saveTechnicianServices --region us-central1 --force
firebase functions:delete saveTechnicianStepData --region us-central1 --force
firebase functions:delete sendChatMessage --region us-central1 --force
firebase functions:delete setPrimaryAddress --region us-central1 --force
firebase functions:delete settleTechnicianBalance --region us-central1 --force
firebase functions:delete startService --region us-central1 --force
firebase functions:delete submitKYC --region us-central1 --force
firebase functions:delete submitPartnerApplication --region us-central1 --force
firebase functions:delete submitServiceRating --region us-central1 --force
firebase functions:delete submitSupportRequest --region us-central1 --force
firebase functions:delete submitTechnicianKyc --region us-central1 --force
firebase functions:delete suspendTechnician --region us-central1 --force
firebase functions:delete technicianAcceptBooking --region us-central1 --force
firebase functions:delete technicianRejectBooking --region us-central1 --force
firebase functions:delete technicianRespondServiceRequest --region us-central1 --force
firebase functions:delete technicianRespondToJob --region us-central1 --force
firebase functions:delete technicianStartJob --region us-central1 --force
firebase functions:delete toggleOnlineStatus --region us-central1 --force
firebase functions:delete toggleTechnicianServiceStatus --region us-central1 --force
firebase functions:delete triggerManualReconciliation --region us-central1 --force
firebase functions:delete triggerTechnicianPayout --region us-central1 --force
firebase functions:delete updateBookingPayment --region us-central1 --force
firebase functions:delete updateCartQuantityCallable --region us-central1 --force
firebase functions:delete updatePricingConfig --region us-central1 --force
firebase functions:delete updateService --region us-central1 --force
firebase functions:delete updateSubService --region us-central1 --force
firebase functions:delete updateTechnicianBankDetails --region us-central1 --force
firebase functions:delete updateTechnicianPersonalDetails --region us-central1 --force
firebase functions:delete updateTechnicianProfile --region us-central1 --force
firebase functions:delete updateTechnicianService --region us-central1 --force
firebase functions:delete updateTechnicianStatus --region us-central1 --force
firebase functions:delete updateUserProfile --region us-central1 --force
firebase functions:delete validateAddressForBooking --region us-central1 --force
firebase functions:delete validateReferralCode --region us-central1 --force
firebase functions:delete verifyBookingStatuses --region us-central1 --force
firebase functions:delete verifyRazorpayPayment --region us-central1 --force
firebase functions:delete verifyTechnicianBankAccount --region us-central1 --force

echo.
echo All old functions deleted!
echo Now deploying new asia-south1 functions...
echo.

firebase deploy --only functions

echo.
echo DEPLOYMENT COMPLETE!
