// Mocks generated by Mockito 5.4.5 from annotations
// in customer_app/test/firebase_functions_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:cloud_functions/cloud_functions.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_positional_boolean_parameters
// ignore_for_file: comment_references
// ignore_for_file: implementation_depends_on_exported_api

class MockFirebaseAuth extends _i1.Mock implements _i2.FirebaseAuth {
  @override
  _i2.User? get currentUser => (super.noSuchMethod(Invocation.getter(#currentUser),
      returnValue: null) as _i2.User?);
  @override
  _i3.Future<_i2.UserCredential> signInWithEmailAndPassword(
          {required String? email, required String? password}) =>
      (super.noSuchMethod(
          Invocation.method(#signInWithEmailAndPassword,
              [], {#email: email, #password: password}),
          returnValue: _i3.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(this, Invocation.method(
                  #signInWithEmailAndPassword, [], {#email: email, #password: password})))) as _i3.Future<_i2.UserCredential>);
  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(Invocation.method(#signOut, []),
          returnValue: _i3.Future<void>.value(),
          returnValueForMissingStub: _i3.Future<void>.value()) as _i3.Future<void>);
}

class MockUser extends _i1.Mock implements _i2.User {
  @override
  String get uid => (super.noSuchMethod(Invocation.getter(#uid), returnValue: '')
      as String);
  @override
  _i3.Future<String> getIdToken(bool? forceRefresh) =>
      (super.noSuchMethod(Invocation.method(#getIdToken, [forceRefresh]),
          returnValue: _i3.Future<String>.value('')) as _i3.Future<String>);
}

class MockFirebaseFunctions extends _i1.Mock
    implements _i4.FirebaseFunctions {
  @override
  _i4.HttpsCallable httpsCallable(String? functionName,
          {_i4.HttpsCallableOptions? options}) =>
      (super.noSuchMethod(
          Invocation.method(#httpsCallable, [functionName], {#options: options}),
          returnValue: _FakeHttpsCallable_1(
              this, Invocation.method(#httpsCallable, [functionName], {#options: options}))) as _i4.HttpsCallable);
}

class MockHttpsCallable extends _i1.Mock implements _i4.HttpsCallable {
  @override
  _i3.Future<_i4.HttpsCallableResult> call([dynamic data]) =>
      (super.noSuchMethod(Invocation.method(#call, [data]),
          returnValue: _i3.Future<_i4.HttpsCallableResult>.value(
              _FakeHttpsCallableResult_2(this, Invocation.method(#call, [data])))) as _i3.Future<_i4.HttpsCallableResult>);
}

class MockHttpsCallableResult extends _i1.Mock
    implements _i4.HttpsCallableResult {
  @override
  dynamic get data => (super.noSuchMethod(Invocation.getter(#data),
      returnValue: null) as dynamic);
}

class _FakeUserCredential_0 extends _i1.Fake
    implements _i2.UserCredential {
  _FakeUserCredential_0(Object parent, Invocation parentInvocation)
      : super._(parent, parentInvocation);
}

class _FakeHttpsCallable_1 extends _i1.Fake implements _i4.HttpsCallable {
  _FakeHttpsCallable_1(Object parent, Invocation parentInvocation)
      : super._(parent, parentInvocation);
}

class _FakeHttpsCallableResult_2 extends _i1.Fake
    implements _i4.HttpsCallableResult {
  _FakeHttpsCallableResult_2(Object parent, Invocation parentInvocation)
      : super._(parent, parentInvocation);
}
