// Mocks generated by Mockito 5.4.5 from annotations
// in customer_app/test/firestore_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:customer_app/core/services/user_location_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_positional_boolean_parameters
// ignore_for_file: comment_references
// ignore_for_file: implementation_depends_on_exported_api

class MockFirebaseFirestore extends _i1.Mock
    implements _i2.FirebaseFirestore {
  @override
  _i2.CollectionReference<Map<String, dynamic>> collection(String? collectionPath) =>
      (super.noSuchMethod(Invocation.method(#collection, [collectionPath]),
          returnValue: _FakeCollectionReference_0<Map<String, dynamic>>(
              this, Invocation.method(#collection, [collectionPath]))) as _i2.CollectionReference<Map<String, dynamic>>);
}

class MockFirebaseAuth extends _i1.Mock implements _i4.FirebaseAuth {
  @override
  _i4.User? get currentUser => (super.noSuchMethod(Invocation.getter(#currentUser),
      returnValue: null) as _i4.User?);
}

class MockUser extends _i1.Mock implements _i4.User {
  @override
  String get uid => (super.noSuchMethod(Invocation.getter(#uid), returnValue: '')
      as String);
}

class MockCollectionReference extends _i1.Mock
    implements _i2.CollectionReference<Map<String, dynamic>> {
  @override
  _i3.Stream<_i2.QuerySnapshot<Map<String, dynamic>>> snapshots(
          {_i2.ListenSource? source}) =>
      (super.noSuchMethod(
          Invocation.method(#snapshots, [], {#source: source}),
          returnValue: _i3.Stream<_i2.QuerySnapshot<Map<String, dynamic>>>.empty()) as _i3.Stream<_i2.QuerySnapshot<Map<String, dynamic>>>);
}

class MockQuery extends _i1.Mock
    implements _i2.Query<Map<String, dynamic>> {
  @override
  _i3.Stream<_i2.QuerySnapshot<Map<String, dynamic>>> snapshots(
          {_i2.ListenSource? source}) =>
      (super.noSuchMethod(
          Invocation.method(#snapshots, [], {#source: source}),
          returnValue: _i3.Stream<_i2.QuerySnapshot<Map<String, dynamic>>>.empty()) as _i3.Stream<_i2.QuerySnapshot<Map<String, dynamic>>>);
}

class MockQuerySnapshot extends _i1.Mock
    implements _i2.QuerySnapshot<Map<String, dynamic>> {
  @override
  List<_i2.QueryDocumentSnapshot<Map<String, dynamic>>> get docs =>
      (super.noSuchMethod(Invocation.getter(#docs),
          returnValue: <_i2.QueryDocumentSnapshot<Map<String, dynamic>>>[]) as List<_i2.QueryDocumentSnapshot<Map<String, dynamic>>>);
}

class MockDocumentSnapshot extends _i1.Mock
    implements _i2.DocumentSnapshot<Map<String, dynamic>> {
  @override
  Map<String, dynamic>? get data => (super.noSuchMethod(Invocation.getter(#data),
      returnValue: null) as Map<String, dynamic>?);
}

class MockUserLocationService extends _i1.Mock
    implements _i5.UserLocationService {
  @override
  _i3.Future<Map<String, dynamic>?> getUserLocationCached() =>
      (super.noSuchMethod(Invocation.method(#getUserLocationCached, []),
          returnValue: _i3.Future<Map<String, dynamic>?>.value(null)) as _i3.Future<Map<String, dynamic>?>);
}

class _FakeCollectionReference_0<T> extends _i1.Fake
    implements _i2.CollectionReference<T> {
  _FakeCollectionReference_0(Object parent, Invocation parentInvocation)
      : super._(parent, parentInvocation);
}
