org.gradle.jvmargs=-Xmx1024m -Xms256m -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -Dkotlin.daemon.jvm.options=-Xmx256m

# Disable parallel & reduce load
org.gradle.parallel=false
org.gradle.configureondemand=false

# Limit workers (VERY IMPORTANT for low RAM)
org.gradle.workers.max=1

# Disable daemon (prevents crash loop)
org.gradle.daemon=false

# Kotlin compiler optimization
kotlin.incremental=false

# Android optimizations
android.useAndroidX=true
android.enableJetifier=true
